config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
  					 path_names: {sign_in: 'login', sign_up: 'signup'}
  get '/users/:id', to: 'users#show'
  get '/', to: 'activities#index'
  get '/custom_route', to: 'activities#custom_route'
  resources :activities
  resources :users
  resources :locations
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :activities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	  before_action :authenticate_user!, only: :show

	def index
		render 'index'
	end

	def show
		@new_marker = Location.new
		@markers_array = Location.all
		render 'show'
		end

	def custom_route
		markers_array = Location.all
		render json: markers_array.to_json
	end

	def new
		@new_thing = Activity.new
		render 'new'
	end

	def create
		@new_thing = Activity.new(activity_params)

		if @new_thing.save
			redirect_to activity_path(@new_thing) 
		else
		redirect_to new_activity_path
		end
	end

	private
	def activity_params
		params.require(:activity).permit(:title, :location, :price)
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	

	def new
		@new_marker = Location.new
		render 'new'
	end

	def create
		@new_marker = Location.new(location_params)

		if @new_marker.save
			redirect_to activity_path(@new_marker) 
		else
		redirect_to activity_path
		end
	end




	private
	def location_params
		params.require(:location).permit(:name, :lat, :lng, :info)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    render 'users/show'
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_configuration, :latitude, :longitude)
    end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.erb
<div class="row-fluid" id="navvy">
    <%= nav_bar fixed: :top, brand: "Local Spice", brand_link: activities_path, responsive: true, id: "top-bar" do %>
    <%= menu_group pull: :right do %>
<% if user_signed_in? %>
    <%= menu_item "Logout", destroy_user_session_path, method: :delete%>
<% else %>
<%= drop_down "Account" do %>
    <%= menu_item "Login", new_user_session_path%>
   <%= menu_item "Sign Up", new_user_registration_path%>
  <% end %>
<% end %>
<% end %>
  <% end%>
  </div>

    <div class="row-fluid">

    <div class="col-sm-4">
      
    </div>

    <div class="col-sm-4" id="get-ready">
      <h1 id="title-text">Get Ready to </h1>

        <button class="center btn" id="explore-btn">
        <h3><a href="/activities/show">Explore</a></h3> 
        </button>
    
    </div>

    <div class="col-sm-4">
      
    </div>
 
      </div>

    <div class="row-fluid">
      
    </div>

    <div class="row-fluid">
      <div id="bottom-panel"></div>
    </div>

app/views/activities/new.html.erb
<h2> Create a thing</h2>

<%= form_for @new_thing do |f| %>
	<div>
	<%= f.label :title %>
	<%= f.text_field :title %>
	</div>

	<div>
	<%= f.label :address %>
	<%= f.text_field :address %>
	</div>

	<div>
	<%= f.label :price %>
	<%= f.text_field :price %>
	</div>
	
    <%= f.button "submit" %>
<% end %>

app/views/activities/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <style type="text/css"> 
  html, body {height: 100%} 
</style> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>Cover Template for Bootstrap</title>
  </head>
  <body>
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '764930830329553',
      xfbml      : true,
      version    : 'v2.7'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

  <%= nav_bar fixed: :top, brand: "Local Spice", brand_link: activities_path, responsive: true do %>
  <%= menu_group do %>
      <%= menu_item "My account" %>
      <%= menu_divider %>
      <%= menu_item "Info" %>
  <% end %>


  <% end%>

    <div id="map" style="width: 100%; height: 900px;"></div>
      <input type="text" name="get-places" id="get-places">

      <button class="btn btn-primary btn-sml" data-toggle="modal" data-target="#myModalHorizontal">
        New marker form
      </button>

      <!-- Modal -->
<div class="modal fade" id="myModalHorizontal" tabindex="-1" role="dialog" 
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" 
                   data-dismiss="modal">
                       <span aria-hidden="true">&times;</span>
                       <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Make your mark:
                </h4>
            </div>
            
            <!-- Modal Body -->
            <div class="modal-body">
                
                <%= form_for @new_marker do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :info %>
  <%= f.text_field :info %>
  </div>
  
  <div>
  <%= f.label :latitude %>
  <%= f.text_field :lat, class: "lat" %>
  </div>

  <div>
  <%= f.label :longitude %>
  <%= f.text_field :lng, class: "lng" %>
  </div>

            </div>
            
            <!-- Modal Footer -->
            <div class="modal-footer">              
    <%= f.submit "submit" %>
<% end %>
            </div>
        </div>
    </div>
</div>
 

 <p>Web app by Young Lad</p><br>
  </body>
</html>
<script type="text/javascript">
$(document).ready(function(){
  var mapStyle = [
  {"elementType":"geometry","stylers":[{"hue":"#ff4400"},{"saturation":-68},{"lightness":-4},{"gamma":0.72}]},{"featureType":"road","elementType":"labels.icon"},{"featureType":"landscape.man_made","elementType":"geometry","stylers":[{"hue":"#0077ff"},{"gamma":3.1}]},{"featureType":"water","stylers":[{"hue":"#00ccff"},{"gamma":0.44},{"saturation":-33}]},{"featureType":"poi.park","stylers":[{"hue":"#44ff00"},{"saturation":-23}]},{"featureType":"water","elementType":"labels.text.fill","stylers":[{"hue":"#007fff"},{"gamma":0.77},{"saturation":65},{"lightness":99}]},{"featureType":"water","elementType":"labels.text.stroke","stylers":[{"gamma":0.11},{"weight":5.6},{"saturation":99},{"hue":"#0091ff"},{"lightness":-86}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"lightness":-48},{"hue":"#ff5e00"},{"gamma":1.2},{"saturation":-23}]},{"featureType":"transit","elementType":"labels.text.stroke","stylers":[{"saturation":-64},{"hue":"#ff9100"},{"lightness":16},{"gamma":0.47},{"weight":2.7}]}
];
  var handler = Gmaps.build('Google');
  var map;
  handler.buildMap({ 
    provider: {
      zoom: 15,
      styles:  mapStyle,
      disableDefaultUI: true
    },
    internal: {id: 'map'} },
    function(){
      map = handler.getMap();
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
    setupAutocomplete();
    ajaxMarkers();
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude
  });
  handler.map.centerOn(marker);
};

function setupAutocomplete(){
  var input = $('#get-places')[0];
  var autocomplete = new google.maps.places.Autocomplete(input);
}

  var contentString = "info string"
  map = handler.getMap();

  map.addListener('click', function(e){
  var marker = new google.maps.Marker({
  position: e.latLng,
          map: map,
          draggable:true
        });
    $('.lat').val(marker.getPosition().lat)
    $('.lng').val(marker.getPosition().lng)
  marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

  var infowindow = new google.maps.InfoWindow({
          content: contentString
    });

  google.maps.event.addListener(marker, 'dragend', function (evt) {
  $('.lat').val(evt.latLng.lat()), $('.lng').val(evt.latLng.lng())
  });
  google.maps.event.addListener(marker, 'dragstart', function (evt) {
    console.log("draggin markah")
  });
});

function ajaxMarkers(){
  $.ajax({
    url: `/custom_route`,
    success: loadMarkers,
    error: console.log('you made an error')
  });
}


function loadMarkers(response){
  var markerArray = response;
  var anotherArray = []
  console.log(markerArray);
 for (var i = 0; i < markerArray.length; i++ ) {
        let lat = Number(markerArray[i].lat);
        let lng = Number(markerArray[i].lng);
        let coords = {lat: lat, lng: lng}
        let info = markerArray[i].info
        console.log(info)
        let marker = new google.maps.Marker({
            position: coords,
            map: map,
            title: info
        }); 
        anotherArray.push(marker);
         let infowindow = new google.maps.InfoWindow({
            content: marker.title
         });
        marker.addListener('click', function(event) {
          infowindow.open(map, marker);
        });
}

}

});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventProgram</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyBb4A6NPZYWz2UA7lTLIJUvflyCfsXMM3A&libraries=places"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<script   src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Volkhov" rel="stylesheet">
<%= csrf_meta_tag %>
</head>
<body>

<%= yield %>
	
</body>
</html>

app/views/locations/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>Cover Template for Bootstrap</title>
  </head>
  <body>
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Local-Spice Map</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#">My account</a></li>
                  <li><a href="#">info</a></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">The Map</h1>
           <div id="input-wrapper" class="pull-right">
      <input class="" type="text" name="get-places" id="get-places">
</div>

<%= form_for @new_marker do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :info %>
  <%= f.text_field :info %>
  </div>
  
  <div>
  <%= f.label :latitude %>
  <%= f.text_field :lat, class: "lat" %>
  </div>

  <div>
  <%= f.label :longitude %>
  <%= f.text_field :lng, class: "lng" %>
  </div>
  
    <%= f.submit "submit" %>
<% end %>

<div style='width: 800px;'>
    <div id="map" style='width: 100%; height: 700px;'></div>
  </div>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Web app by Young Lad</p>
            </div>
          </div>

        </div>

      </div>

    </div>
  </body>
</html>


<script type="text/javascript">
$(document).ready(function(){
  var mapStyle = [
  {"elementType":"geometry","stylers":[{"hue":"#ff4400"},{"saturation":-68},{"lightness":-4},{"gamma":0.72}]},{"featureType":"road","elementType":"labels.icon"},{"featureType":"landscape.man_made","elementType":"geometry","stylers":[{"hue":"#0077ff"},{"gamma":3.1}]},{"featureType":"water","stylers":[{"hue":"#00ccff"},{"gamma":0.44},{"saturation":-33}]},{"featureType":"poi.park","stylers":[{"hue":"#44ff00"},{"saturation":-23}]},{"featureType":"water","elementType":"labels.text.fill","stylers":[{"hue":"#007fff"},{"gamma":0.77},{"saturation":65},{"lightness":99}]},{"featureType":"water","elementType":"labels.text.stroke","stylers":[{"gamma":0.11},{"weight":5.6},{"saturation":99},{"hue":"#0091ff"},{"lightness":-86}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"lightness":-48},{"hue":"#ff5e00"},{"gamma":1.2},{"saturation":-23}]},{"featureType":"transit","elementType":"labels.text.stroke","stylers":[{"saturation":-64},{"hue":"#ff9100"},{"lightness":16},{"gamma":0.47},{"weight":2.7}]}
];
  var handler = Gmaps.build('Google');
  var map;
  handler.buildMap({ 
    provider: {
      zoom: 15,
      styles:  mapStyle,
      disableDefaultUI: true
    },
    internal: {id: 'map'} },
    function(){
      map = handler.getMap();
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);

});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude
  });
  handler.map.centerOn(marker);
};
// function setupAutocomplete(){
//   var input = $('#get-places')[0];
//   var autocomplete = new google.maps.places.Autocomplete(input)
//   autocomplete.addListener('place_changed', function(){
//     var place = autocomplete.getPlace();
//     if (place.geometry.location){
//       map.setCenter(place.geometry.location);
//       map.setZoom(17);
//       // createMarker(place.geometry.location)
//       createEvent(place.geometry.location)
      
//     }else{
//       alert("The place has no location")
//     }
//   });
// }
   var contentString = "info string"

  map = handler.getMap();
map.addListener('click', function(e){
  var marker = new google.maps.Marker({
  position: e.latLng,
          map: map,
          draggable:true
        });
    $('.lat').val(marker.getPosition().lat)
    $('.lng').val(marker.getPosition().lng)

  marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

  var infowindow = new google.maps.InfoWindow({
          content: contentString
    });

  google.maps.event.addListener(marker, 'dragend', function (evt) {
  $('.lat').val(evt.latLng.lat()), $('.lng').val(evt.latLng.lng())
  });
  google.maps.event.addListener(marker, 'dragstart', function (evt) {
    console.log("draggin markah")
  });
});


});
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Description</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @user.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @user.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>